version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "8081:8080"
    environment:
      - BACKEND_URL=http://backend:5000/api/data
    depends_on:
      - backend

  logger:
    build: ./logger
    depends_on:
      - backend